# Generated by Django 6.0.5 on 2026-05-31 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='uploaded_file',
        ),
        migrations.CreateModel(
            name='FileUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('bank_statement', 'Bank Statement'), ('internal_ledger', 'Internal Ledger'), ('payment_gateway', 'Payment Gateway File')], max_length=30)),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed')], default='processed', max_length=20)),
                ('rows_extracted', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='reconciliation.reconciliationsession')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='upload_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='reconciliation.fileuploadlog'),
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
